version: "3.8"

services:
  # MySQLroot
  mysql:
    image: mysql:latest
    container_name: mysql-filmlist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Filmlist-Database
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet

volumes:
  mysql_data:

networks:
  mynet:
    driver: bridge